Accelerate strategy
trikset/trik-desktop-gamepad pull request #5
Opened 2017-05-04 20:03 UTC by kbatoev

2017-05-05 16:33 UTC, iakov commented on accelerateStrategy.cpp
> +	indeces = {
indices?

2017-05-05 16:43 UTC, iakov requested changes

2017-05-05 16:43 UTC, iakov commented on accelerateStrategy.cpp
> +	connect(&stopTimerForPad2, SIGNAL(timeout()), padsMapper, SLOT(map()));
Might be single timer for both pads is enough?

2017-05-05 16:43 UTC, iakov commented on accelerateStrategy.cpp
> +	if (mPressedKeys.size()) {
Must be !mPressedKeys.empty(). Never use .size() to test if collection is empty

2017-05-06 08:59 UTC, kbatoev commented on accelerateStrategy.cpp
> +	connect(&stopTimerForPad2, SIGNAL(timeout()), padsMapper, SLOT(map()));
There was one pad for both pads in the previous version. The problem was when I pressed pad1, then pressed pad2, released pad1, and released pad2 in some time (ex. 30 seconds). And only in the end there were two commands: pad 1 up, pad 2 up, but I expected command "pad 1 up", when I released pad1.
So, I decided to use timer per pad.

2017-05-07 20:19 UTC, merged